name: Upptime

on:
  schedule:
    - cron: '*/5 * * * *' # Vérifie toutes les 5 minutes
  workflow_dispatch:

jobs:
  upptime:
    runs-on: ubuntu-latest
    steps:
      - name: Check URL
        uses: upptime/upptime@main
        with:
          url: 'https://replit.com/@ThomasDa6/crypto-fear-and-greed-bot'
